-- AlterTable
ALTER TABLE "User" ADD COLUMN "workingHourStart" INTEGER NOT NULL DEFAULT 480;
ALTER TABLE "User" ADD COLUMN "workingHourEnd" INTEGER NOT NULL DEFAULT 1020;
ALTER TABLE "User" ADD COLUMN "timeFormat" TEXT NOT NULL DEFAULT '24h';

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN "doneAt" DATETIME;
